### ISSUE TITLE
Unable to Clone

### ISSUE THREAD

**Issue by ShanaBreland** [rogeramitchell/react-salesforce-dug-oct-17#1]
Unable to clone repo as instructed.
`MacBook-Pro:Users LaShana$ git clone https://github.com/rogeramitchell/react-salesforce-dug-oct-17.git
fatal: could not create work tree dir 'react-salesforce-dug-oct-17': Permission denied`

**Comment by rogeramitchell** [comment]
Hey @Sportychic2089, sorry to hear this is happening!

When you open up Terminal.app, are you able to do the following?
`cd Desktop`

Then, run the git clone command:
`git clone https://github.com/rogeramitchell/react-salesforce-dug-oct-17.git`

**Comment by ShanaBreland** [comment]
I was able to clone successfully! I see my issue now. Thank you so much @rogeramitchell. That's what I get for trying to do things when I'm sleepy. Enjoy your weekend!

**Comment by rogeramitchell** [comment]
No worries! Let me know if you have any other questions / comments, and enjoy your weekend too!
